language: node_js
node_js:
  - 21

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

## Tagging
  - docker tag udagram-api-feed phani5757/udagram-api-feed:v1
  - docker tag udagram-api-user phani5757/udagram-api-user:v1
  - docker tag udagram-frontend phani5757/udagram-frontend:v1
  - docker tag udagram-reverseproxy phani5757/udagram-reverseproxy:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/simple-node

## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push phani5757/udagram-api-feed:v1
  - docker push phani5757/udagram-api-user:v1
  - docker push phani5757/udagram-frontend:v1
  - docker push phani5757/udagram-reverseproxy:v1
