apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  POSTGRES_HOST: "database-1.csjlzi8eaygr.us-east-1.rds.amazonaws.com"
  POSTGRES_DB: "postgres"
  AWS_BUCKET: "img-processing-581304011193-project"
  AWS_REGION: "us-east-1"
  AWS_PROFILE: "default"
  URL: "http://localhost:8100"
  PORT: "8100"
