version: 2.1

jobs:
  build_and_push_docker_image:
    docker:
        - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: |
            docker build -t udagram-api-feed ../udagram-api-feed
            docker build -t udagram-api-user ../udagram-api-user
            docker build -t udagram-frontend ../udagram-frontend
            docker build -t udagram-reverseproxy ../udagram-reverseproxy

            docker tag udagram-api-feed phani5757/udagram-api-feed:v1
            docker tag udagram-api-user phani5757/udagram-api-user:v1
            docker tag udagram-frontend phani5757/udagram-frontend:v1
            docker tag udagram-reverseproxy phani5757/udagram-reverseproxy:v1

            # Log in to Docker Hub using environment variables
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin


            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push phani5757/udagram-api-feed:v1
            docker push phani5757/udagram-api-user:v1
            docker push phani5757/udagram-frontend:v1
            docker push phani5757/udagram-reverseproxy:v1
          name: Build Images






